name: Auto Publish Update (Manual)
on:
  workflow_dispatch: #åªæœ‰æˆ‘å»ç½‘é¡µç‚¹æŒ‰é’®æ‰å‘ï¼Œé˜²æ­¢æ‰‹æ»‘
    inputs:
      message:
        description: 'Update Message'
        required: true
        default: 'General bug fixes'

jobs:
  update:
    name: ğŸš€ EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Check out Git repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: âš™ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # è¿˜æ˜¯ç”¨ä¹‹å‰é…ç½®å¥½çš„é‚£ä¸ª Token

      - name: ğŸ“¦ Install dependencies
        run: npm install

      # ğŸ”¥ æ ¸å¿ƒæ­¥éª¤ï¼šå‘å¸ƒçƒ­æ›´æ–°
      - name: ğŸš€ Publish Update
        run: |
          # ä½¿ç”¨ä½ åœ¨ç½‘é¡µè¾“å…¥çš„æè¿°
          eas update --branch preview --message "${{ github.event.inputs.message }}"